### ISSUE TITLE
Have menus adapt to user's customized bindings

### ISSUE THREAD

**Issue by thomastthai** [jaclu/tmux-menus#48]
This plugin is already nicely over-engineered. Why not take it to the next level of over-engineering? :)

Currently, the menus are hardcoded with certain keybindings that could be different than the user's settings. Having the menu "read" (`tmux list-keys`, `tmux show-keys`, and/or other ways) the user key bindings and display those in the menus would help reinforce memory and give them the menu as another access point. This is a major reason for nvim's which-key success.

For example, part of my `tmux.conf` include:

```tmux
bind | split-window -h -c "#{pane_current_path}"
bind \\ split-window -fh -c "#{pane_current_path}"
bind '-' split-window -v -c "#{pane_current_path}"
bind '_' split-window -fv -c "#{pane_current_path}"
```

**Comment by jaclu** [comment]
I always apreciate suggestions, but Im not sure what you mean in this case. Previously I tried to always list the default key-bindings for items when there was one, but in the end it made the menus a bit bloated, so I recently dropped it. 
Is your suggestion to go all in and display the current bindings where appicable? In that case I do agree it would be a nice feature to be remainded of the current config. But it would raise the bar considerably, since then each other shortcut in the menu would have to be checked so that there are no duplicates

**Comment by jaclu** [comment]
Regarding using yaml to define menus, sure could be done, but not sure if it would make things more convenient when defining dynamic items like the Panes menu, using shell script gives a fairly simplistic menu design, and allows normal script logic when examining states deciding dynamic items. I have mostly used yaml when doing docker and ansible, so perhaps scripting can be included without too much over head?

**Comment by jaclu** [comment]
but sure i you think my menu design concept is hard to understand, that might need to be adressed

**Comment by jaclu** [comment]
GPT suggested that tmux conditionals could be done something like this:

```yaml
menus:
  - name: "My Tmux Menu"
    items:
      - label: "Do Action If Pane Marked"
        command: |
          if-shell 'tmux list-panes -F "#{?pane_marked,1,0}" | grep -q 1' \
            'tmux display-message "A pane is marked!"' \
            'tmux display-message "No pane is marked."'
      - label: "Other Action"
        command: "tmux split-window"
```

No entirely sure that could be seen as less confusing :) - any thoughts?
